# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maciej Mionskowski
email: business@mionskowski.pl
description: "Maciej maciekmm Mionskowski - Java/Go backend developer"
baseurl: ""
url: "https://mionskowski.pl"
paginate: 3
paginate_path: "/:num/"

# Build settings
highlighter: rouge
markdown: kramdown
markdown_ext:  mkd,md

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
