title: Maciej Mionskowski
email: business@mionskowski.pl
description: "Maciej Mionskowski - Software Engineer"
baseurl: ""
url: "https://mionskowski.pl"
paginate: 10
paginate_path: "/:num/"

collections:
  tils:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "tils/*"
    values:
      type: til

# Build settings
highlighter: rouge
markdown: kramdown
markdown_ext:  mkd,md

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

plugins:
  - jekyll-sitemap
  - jekyll-paginate
