# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maciej<span class="lowlight">'s blog</span>
email: business@maciekmm.net
description: "Maciej maciekmm Mionskowski - golang developer, backend systems, webscraping, java development."
baseurl: ""
url: "https://maciekmm.net"

# Build settings
highlighter: pygments
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

permalink: /:title

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

gems:
  - jekyll-sitemap
  - jekyll-mentions
